prometheus-blackbox-exporter:
  pspEnable: false

  config:
    modules:
      http_200_onet_pl:
        prober: http
        timeout: 5s
        http:
          valid_status_codes: [200]
          method: "GET"
          fail_if_ssl: false
          fail_if_not_ssl: true
          tls_config:
            insecure_skip_verify: true
